package model;
// Generated 2018/3/8 �U�� 08:10:17 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TrackingId generated by hbm2java
 */
@Embeddable
public class TrackingId implements java.io.Serializable {

	private String MAccount;
	private String stockId;

	public TrackingId() {
	}

	public TrackingId(String MAccount, String stockId) {
		this.MAccount = MAccount;
		this.stockId = stockId;
	}

	@Column(name = "m_account", nullable = false, length = 30)
	public String getMAccount() {
		return this.MAccount;
	}

	public void setMAccount(String MAccount) {
		this.MAccount = MAccount;
	}

	@Column(name = "stock_id", nullable = false, length = 4)
	public String getStockId() {
		return this.stockId;
	}

	public void setStockId(String stockId) {
		this.stockId = stockId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TrackingId))
			return false;
		TrackingId castOther = (TrackingId) other;

		return ((this.getMAccount() == castOther.getMAccount()) || (this.getMAccount() != null
				&& castOther.getMAccount() != null && this.getMAccount().equals(castOther.getMAccount())))
				&& ((this.getStockId() == castOther.getStockId()) || (this.getStockId() != null
						&& castOther.getStockId() != null && this.getStockId().equals(castOther.getStockId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getMAccount() == null ? 0 : this.getMAccount().hashCode());
		result = 37 * result + (getStockId() == null ? 0 : this.getStockId().hashCode());
		return result;
	}

	@Override
	public String toString() {
		return "TrackingId [MAccount=" + MAccount + ", stockId=" + stockId + "]";
	}
	
	

}
