package model;
// Generated 2018/3/8 �U�� 08:10:17 by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Tracking generated by hbm2java
 */
@Entity
@Table(name = "TRACKING", schema = "dbo", catalog = "Project1")
public class Tracking implements java.io.Serializable {

	private TrackingId id;
	private Integer alertHigh;
	private Integer alertLow;

	public Tracking() {
	}

	public Tracking(TrackingId id) {
		this.id = id;
	}
	
	public Tracking(TrackingId id, Integer alertHigh, Integer alertLow) {
		this.id = id;
		this.alertHigh = alertHigh;
		this.alertLow = alertLow;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "MAccount", column = @Column(name = "m_account", nullable = false, length = 30)),
			@AttributeOverride(name = "stockId", column = @Column(name = "stock_id", nullable = false, length = 4)) })
	public TrackingId getId() {
		return this.id;
	}

	public void setId(TrackingId id) {
		this.id = id;
	}

	@Column(name = "alert_high")
	public Integer getAlertHigh() {
		return this.alertHigh;
	}

	public void setAlertHigh(Integer alertHigh) {
		this.alertHigh = alertHigh;
	}

	@Column(name = "alert_low")
	public Integer getAlertLow() {
		return this.alertLow;
	}

	public void setAlertLow(Integer alertLow) {
		this.alertLow = alertLow;
	}

	@Override
	public String toString() {
		return "Tracking [id=" + id + ", alertHigh=" + alertHigh + ", alertLow=" + alertLow + "]";
	}

	
	

}
